Repository GodotCommunityGamesOrg/Lost-Pilot, pull requests merged in 2024-11, with the labels that each got.

#1 Character turn based movement
  Assets/DoorSpriteSelected.png
  Assets/DoorSpriteSelected.png.import
  Assets/DoorSpriteSheet.png
  Assets/DoorSpriteSheet.png.import
  Assets/Gugi-Regular.ttf
  Assets/Gugi-Regular.ttf.import
  Assets/icon.svg
  Assets/icon.svg.import
  Scenes/Player/MapGenerator.gd
  Scenes/Player/Player.tscn
  Scenes/Player/Wor4707.tmp
  Scenes/Player/World.tscn
  Scenes/door.tscn
  Scripts/Global/Global.gd
  Scripts/Global/UtilityFunctions.gd
  Scripts/InteractionSystem/Base/InteractableObj.gd
  Scripts/InteractionSystem/Base/Template/Int7C3.tmp
  Scripts/InteractionSystem/Base/Template/InteractableObjTemplate.tscn
  Scripts/InteractionSystem/Door.gd
  Scripts/Player/Player.gd
  Scripts/Templates/InteractableObject/InteractableObjectTemplate.gd
  Scripts/UI/Base/CircleMenuButton.gd
  Scripts/UI/Base/UserInterface.gd
  Scripts/UI/Base/WheelOption.gd
  addons/godot-git-plugin/.DS_Store
  addons/godot-git-plugin/LICENSE
  addons/godot-git-plugin/THIRDPARTY.md
  addons/godot-git-plugin/git_plugin.gdextension
  addons/godot-git-plugin/plugin.cfg
  addons/godot-git-plugin/win64/libgit_plugin.windows.editor.x86_64.dll
  addons/godot-git-plugin/win64/libgit_plugin.windows.editor.x86_64.exp
  addons/godot-git-plugin/win64/libgit_plugin.windows.editor.x86_64.lib
  addons/godot-git-plugin/win64/~libgit_plugin.windows.editor.x86_64.dll
  icon.svg
  icon.svg.import
  project.godot
Labels: documentation, enhancement

#8 Adding more information to README Lost Pilot game project
  README.md
Labels: documentation

#10 Improved Menu system.
  Assets/Gugi-Regular.ttf.import
  Assets/UI/FinishedIndicator_64x32.png
  Assets/UI/FinishedIndicator_64x32.png.import
  Assets/UI/GitHub_Logo.png
  Assets/UI/GitHub_Logo.png.import
  Assets/UI/GrayPanel64x64.png
  Assets/UI/GrayPanel64x64.png.import
  Assets/UI/Panel64x64.png
  Assets/UI/Panel64x64.png.import
  Assets/UI/Selected.png
  Assets/UI/Selected.png.import
  Assets/UI/TransparentGrayPanel64x64.png
  Assets/UI/TransparentGrayPanel64x64.png.import
  Assets/UI/TransparentPanel64x64.png
  Assets/UI/TransparentPanel64x64.png.import
  Documentation/MenuSystem - How to use.txt
  Scenes/Main/main.tscn
  Scenes/MenuTemplate.tscn
  Scenes/Menus/credits_menu.tscn
  Scenes/Menus/in_game_menu.tscn
  Scenes/Menus/main_menu.tscn
  Scenes/Menus/pause_menu.tscn
  Scenes/Menus/settings_menu.tscn
  Scenes/SpaceStation/SpaceStation.tscn
  Scripts/Global/GameManager.gd
  Scripts/InteractionSystem/Base/Template/obj_template.gd
  Scripts/Menu System/MenuBase.gd
  Scripts/Menu System/MenuSystem.gd
  Scripts/Menus/Settings_menu.gd
  Scripts/Menus/credits_menu.gd
  Scripts/Menus/in_game_menu.gd
  Scripts/Menus/main_menu.gd
  Scripts/Menus/pause_menu.gd
  project.godot
Labels: enhancement
